services:
  blog-app:
    image: postgres:16.4
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    volumes:
      - blog-app-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  blog-app-data: