name: Deploy Spring and VueJS App (Railway)

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4  # Checkout the code from the repository
      - uses: dorny/paths-filter@v2  # Filter the paths that have been changed
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  build-and-test-backend:
    name: Build and Test Application (Backend)
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ needs.deploy.outputs.backend == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test Backend
        working-directory: ./backend
        run: mvn clean verify

  deploy-backend-preview:
    name: Deploy Backend to Railway Preview
    runs-on: ubuntu-latest
    needs: build-and-test-backend
    if: ${{ needs.deploy.outputs.backend == 'true' && github.event_name == 'pull_request' && github.event.action != 'closed' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway (Preview Backend)
        uses: ayungavis/railway-preview-deploy@v1.0.2
        with:
          railway_api_token: ${{ secrets.RAILWAY_TOKEN }}
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_name: 'staging-backend'
          preview_environment_name: 'pr-${{ github.event.pull_request.number }}'
          branch_name: ${{ github.head_ref }}

  vitest-frontend-tests:
    name: Run Vitest Tests for Frontend
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ needs.deploy.outputs.frontend == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Vitest Tests
        working-directory: ./frontend
        run: npm run test

  deploy-frontend-preview:
    name: Deploy Frontend to Railway Preview
    runs-on: ubuntu-latest
    needs: vitest-frontend-tests
    if: ${{ needs.deploy.outputs.frontend == 'true' && github.event_name == 'pull_request' && github.event.action != 'closed' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway (Preview Frontend)
        uses: ayungavis/railway-preview-deploy@v1.0.2
        with:
          railway_api_token: ${{ secrets.RAILWAY_TOKEN }}
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_name: 'staging-frontend'
          preview_environment_name: 'pr-${{ github.event.pull_request.number }}'
          branch_name: ${{ github.head_ref }}

  cleanup-preview:
    name: Cleanup Railway Preview Environment
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true || github.event.action == 'closed' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cleanup Railway Backend Environment
        uses: ayungavis/railway-preview-deploy@v1.0.2
        with:
          railway_api_token: ${{ secrets.RAILWAY_TOKEN }}
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_name: 'staging-backend'
          preview_environment_name: 'pr-${{ github.event.pull_request.number }}'
          branch_name: ${{ github.head_ref }}

      - name: Cleanup Railway Frontend Environment
        uses: ayungavis/railway-preview-deploy@v1.0.2
        with:
          railway_api_token: ${{ secrets.RAILWAY_TOKEN }}
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_name: 'staging-frontend'
          preview_environment_name: 'pr-${{ github.event.pull_request.number }}'
          branch_name: ${{ github.head_ref }}

  deploy-staging:
    name: Deploy to Railway (Staging)
    runs-on: ubuntu-latest
    needs: [ build-and-test-backend, vitest-frontend-tests ]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway (Staging Backend)
        uses: ayungavis/railway-preview-deploy@v1.0.2
        with:
          railway_api_token: ${{ secrets.RAILWAY_TOKEN }}
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_name: 'staging-backend'
          branch_name: main
          preview_environment_name: 'staging-backend'

      - name: Deploy to Railway (Staging Frontend)
        uses: ayungavis/railway-preview-deploy@v1.0.2
        with:
          railway_api_token: ${{ secrets.RAILWAY_TOKEN }}
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_name: 'staging-frontend'
          branch_name: main
          preview_environment_name: 'staging-frontend'